### ISSUE TITLE
Line break will double 'Hit' 

### ISSUE THREAD

**Issue by hermitgreen** [pyutils/line_profiler#106]
I have test code
```python
class T:
    def __init__(self, data):
        self.data = data


@profile
def main():
    a = T(1)
    d = T(T(1))
    e = T(
        T(1))
    g = T(T(T(1)))
    h = T(
        T(
        T(1)))
    i = T(
        T(
        T(
        T(1))))

main()
```
then I try
```shell
kernprof -l test.py
python -m line_profiler test.py.lprof
```

then I get

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     6                                           @profile
     7                                           def main():
     8         1          5.0      5.0     29.4      a = T(1)
     9         1          2.0      2.0     11.8      d = T(T(1))
    10         2          2.0      1.0     11.8      e = T(
    11         1          1.0      1.0      5.9          T(1))
    12         1          2.0      2.0     11.8      g = T(T(T(1)))
    13         2          0.0      0.0      0.0      h = T(
    14         2          0.0      0.0      0.0          T(
    15         1          0.0      0.0      0.0          T(1)))
    16         2          1.0      0.5      5.9      i = T(
    17         2          2.0      1.0     11.8          T(
    18         2          1.0      0.5      5.9          T(
    19         1          1.0      1.0      5.9          T(1))))
```

It's seems line break will double hit and get a wrong per hit time. Is this a bug?

**Comment by embray** [comment]
I just discovered this as well. It seems to be a regression because I was comparing the same code on Python 2 (with line_profiler < 3.0) and on Python 3 with latest version, and this did not happen on the Python 2 version.

Relatedly it seems on Python 2 the first line does not have any time recorded, whereas on Python 3 it shows the full time for that line but it's double-counted, leading to misleading results.

Not sure if this is part of an intentional change or not. Will investigate further...

**Comment by Erotemic** [comment]
@embray Thank you for the additional details. Any further contribution on this issue would be very much appreciated. :) I don't have a firm grasp on the issue. 

There is also a chance that the bug was fixed in the 4.0 branch: https://github.com/pyutils/line_profiler/pull/165 but it hasn't been verified either way.

**Comment by embray** [comment]
From what I can tell it kind of makes sense. The first count is from any sub-expressions on the first physical line (typically ~0us if it's just something like `x = func(`), while the second count is for the entire logical expression/statement.

A little confusing but makes sense in a way. Maybe just a documentation patch is sufficient. But I'll try the 4.0 branch.

**Comment by usbhub** [comment]
I'm still having this issue with line-profiler 4.1.2. Seems to me like a bug as just separating arguments onto a new line to reduce line width will make the hits double counted and half the real per hit time.

**Comment by Rainlin007** [comment]
I'm still having this issue with line-profiler 4.1.3.
