### ISSUE TITLE
ModuleNotFoundError: No module named 'line_profiler._line_profiler'

### ISSUE THREAD

**Issue by mikekeda** [pyutils/line_profiler#50]
I installed the 3.2.0 version with pip and I'm getting this error on the line:
https://github.com/pyutils/line_profiler/blob/master/line_profiler/line_profiler.py#L28
There is no `_line_profiler` file
There was not error on 3.1.0 version

pip 21.0.1
line_profiler 3.2.0
Python  3.7.0

**Comment by vertti** [comment]
Same here. Was driving me nuts as it worked on friday and I checked github: no new releases. But yeah, new release was done today.

**Comment by HSIF1911** [comment]
Anyone has solution to this issue? Really need help, please....

**Comment by HSIF1911** [comment]
> Same here. Was driving me nuts as it worked on friday and I checked github: no new releases. But yeah, new release was done today.

How did u fix this dude?

**Comment by vertti** [comment]
> > Same here. Was driving me nuts as it worked on friday and I checked github: no new releases. But yeah, new release was done today.
> 
> How did u fix this dude?

Just rolled back to using 3.0.2 version until this is fixed.

**Comment by HSIF1911** [comment]
> > > Same here. Was driving me nuts as it worked on friday and I checked github: no new releases. But yeah, new release was done today.
> > 
> > 
> > How did u fix this dude?
> 
> Just rolled back to using 3.0.2 version until this is fixed.

Thank u dude, it works.

**Comment by cliffckerr** [comment]
Confirm this is working again, will close my issue.

**Comment by mikekeda** [comment]
3.2.0 was yanked,
if you do pip install line-profiler, 3.1.0 will be installed
https://pypi.org/project/line-profiler/#history

**Comment by cliffckerr** [comment]
@mikekeda Hmm -- I still see it listed in https://pypi.org/simple/line-profiler/, but you're right that GitHub Actions are now passing again, which is what I care about :) Seems to be resolved so I'll close my issue (again).

**Comment by luzik** [comment]
When line_profiler is in req on other packages, affected 3.2.0 is installed

**Comment by Erotemic** [comment]
@luzik, noted, I will attempt to release 3.2.1 tonight. I believe the publish scripts are now working, although I've been putting off actually pressing the button until I have time to verify that it worked and mitigate catastrophes if they occur.

**Comment by Erotemic** [comment]
@luzik the new release is live and on pypi. Please verify everything works correctly. I've switched to a new release process, so I'm hoping everything went ok.

**Comment by oxhaowang** [comment]
Tried the new release, still generating ModuleNotFoundError: No module name 'line_profiler._line_profiler'. 

Python verson :3.9

Then installed with git repo version( pip3 install git+https://github.com/pyutils/line_profiler), it works now for me.

**Comment by cliffckerr** [comment]
@oxhaowang On which OS? I tried with a fresh Conda 3.9 virtual environment on Ubuntu, and it worked fine for me:
```
conda create -n tmp_lp python=3.9
conda activate tmp_lp
(tmp_lp) host:~> pip install line_profiler
Collecting line_profiler
  Downloading line_profiler-3.2.1-cp39-cp39-manylinux2010_x86_64.whl (66 kB)
     |████████████████████████████████| 66 kB 2.0 MB/s 
(tmp_lp) host:~> python
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import line_profiler as lp
>>> 
```

**Comment by oxhaowang** [comment]
@cliffckerr Mac Big Sur. Could it be my python enviroment is a mess...

**Comment by soroshsabz** [comment]
I have the same problem with 3.2.1 version on Windows 10 with Visual Studio 2019

**Comment by skupr-anaconda** [comment]
This bug on all platforms (linux, osx, ppc64le, win32, win64 with py36-py39) when it's building with conda build but only in test environment:

```
TEST START: output-artifacts/linux-64/line_profiler-3.2.1-py36hff7bd54_0.tar.bz2
Renaming work directory '/tmp/build/80754af9/line_profiler_1619527124040/work' to '/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64'
INFO:conda_build.utils:Renaming work directory '/tmp/build/80754af9/line_profiler_1619527124040/work' to '/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64'
INFO conda_build.utils:shutil_move_more_retrying(2077): Renaming work directory '/tmp/build/80754af9/line_profiler_1619527124040/work' to '/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64'
shutil.move(work)=/tmp/build/80754af9/line_profiler_1619527124040/work, dest=/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64)
INFO:conda_build.utils:shutil.move(work)=/tmp/build/80754af9/line_profiler_1619527124040/work, dest=/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64)
INFO conda_build.utils:shutil_move_more_retrying(2084): shutil.move(work)=/tmp/build/80754af9/line_profiler_1619527124040/work, dest=/tmp/build/80754af9/line_profiler_1619527124040/work_moved_line_profiler-3.2.1-py36hff7bd54_0_linux-64)
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /tmp/build/80754af9/line_profiler_1619527124040/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place


The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main                 defaults                                   
    backcall:         0.2.0-pyhd3eb1b0_0       defaults                                   
    ca-certificates:  2021.4.13-h06a4308_1     defaults                                   
    certifi:          2020.12.5-py36h06a4308_0 defaults                                   
    decorator:        5.0.6-pyhd3eb1b0_0       defaults                                   
    ipython:          7.16.1-py36h5ca1d4c_0    defaults                                   
    ipython_genutils: 0.2.0-pyhd3eb1b0_1       defaults                                   
    jedi:             0.17.0-py36_0            defaults                                   
    ld_impl_linux-64: 2.33.1-h53a641e_7        defaults                                   
    libffi:           3.3-he6710b0_2           defaults                                   
    libgcc-ng:        9.1.0-hdf63c60_0         defaults                                   
    libstdcxx-ng:     9.1.0-hdf63c60_0         defaults                                   
    line_profiler:    3.2.1-py36hff7bd54_0     file:///tmp/build/80754af9/output-artifacts
    ncurses:          6.2-he6710b0_1           defaults                                   
    openssl:          1.1.1k-h27cfd23_0        defaults                                   
    parso:            0.8.2-pyhd3eb1b0_0       defaults                                   
    pexpect:          4.8.0-pyhd3eb1b0_3       defaults                                   
    pickleshare:      0.7.5-pyhd3eb1b0_1003    defaults                                   
    prompt-toolkit:   3.0.17-pyh06a4308_0      defaults                                   
    ptyprocess:       0.7.0-pyhd3eb1b0_2       defaults                                   
    pygments:         2.8.1-pyhd3eb1b0_0       defaults                                   
    python:           3.6.13-hdb3f193_0        defaults                                   
    readline:         8.1-h27cfd23_0           defaults                                   
    setuptools:       52.0.0-py36h06a4308_0    defaults                                   
    six:              1.15.0-py36h06a4308_0    defaults                                   
    sqlite:           3.35.4-hdfb4753_0        defaults                                   
    tk:               8.6.10-hbc83047_0        defaults                                   
    traitlets:        4.3.3-py36_0             defaults                                   
    wcwidth:          0.2.5-py_0               defaults                                   
    xz:               5.2.5-h7b6447c_0         defaults                                   
    zlib:             1.2.11-h7b6447c_3        defaults                                   

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/tmp/build/80754af9/line_profiler_1619527124040/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
export SRC_DIR=/tmp/build/80754af9/line_profiler_1619527124040/test_tmp
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD_GOLD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_PREFIX_PATH=:$PREFIX:/tmp/build/80754af9/line_profiler_1619527124040/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include
+CPP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX/include
+GCC_AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC_NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+GXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++
INFO: deactivate-gxx_linux-64.sh made the following environmental changes:
-CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-CXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++
-DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-GXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++
INFO: deactivate-gcc_linux-64.sh made the following environmental changes:
-CC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cc
-CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-CMAKE_PREFIX_PATH=:$PREFIX:/tmp/build/80754af9/line_profiler_1619527124040/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr
-_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
-CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include
-CPP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp
-DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/line_profiler-3.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX/include
-GCC_AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
-GCC_NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
-GCC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc
-GCC_RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
-LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
INFO: deactivate-binutils_linux-64.sh made the following environmental changes:
-ADDR2LINE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-addr2line
-AR=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ar
-AS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-as
-CXXFILT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++filt
-ELFEDIT=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-elfedit
-GPROF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gprof
-LD_GOLD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld.gold
-LD=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ld
-NM=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-nm
-OBJCOPY=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objcopy
-OBJDUMP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-objdump
-RANLIB=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-ranlib
-READELF=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-readelf
-SIZE=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-size
-STRINGS=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strings
-STRIP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-strip
Traceback (most recent call last):
  File "/tmp/build/80754af9/line_profiler_1619527124040/test_tmp/run_test.py", line 5, in <module>
import: 'kernprof'
import: 'line_profiler'
    import line_profiler
  File "/tmp/build/80754af9/line_profiler_1619527124040/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/site-packages/line_profiler/__init__.py", line 10, in <module>
    from .line_profiler import __version__
  File "/tmp/build/80754af9/line_profiler_1619527124040/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/site-packages/line_profiler/line_profiler.py", line 26, in <module>
    from ._line_profiler import LineProfiler as CLineProfiler
ModuleNotFoundError: No module named 'line_profiler._line_profiler'
Tests failed for line_profiler-3.2.1-py36hff7bd54_0.tar.bz2 - moving package to /tmp/build/80754af9/broken
WARNING:conda_build.build:Tests failed for line_profiler-3.2.1-py36hff7bd54_0.tar.bz2 - moving package to /tmp/build/80754af9/broken
WARNING conda_build.build:tests_failed(2956): Tests failed for line_profiler-3.2.1-py36hff7bd54_0.tar.bz2 - moving package to /tmp/build/80754af9/broken
TESTS FAILED: line_profiler-3.2.1-py36hff7bd54_0.tar.bz2
```

**Comment by soroshsabz** [comment]
@mikekeda  please reopen this issue

**Comment by Erotemic** [comment]
I believe this issue was fixed. Reopen if I am mistaken.

**Comment by soroshsabz** [comment]
@Erotemic 

In version 3.3.0 my problem is resolved

thanks

**Comment by toandeptraibodoiqua** [comment]
Still have the same problem
Python 3.9.5
line-profiler 3.3.0

**Comment by Erotemic** [comment]
@toandeptraibodoiqua Are you absolutely sure? It should have been fixed in 3.3.0. I just released 3.3.1, try seeing if updating fixes your issues. If not please open a new issue with details about your OS, Python distribution, line_profiler distribution, and ideally a MWE.

**Comment by toandeptraibodoiqua** [comment]
@Erotemic Thank you. The issue was fixed at the end. But I don't know exactly how.
